export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_FILLING: "ADD_FILLING" = "ADD_FILLING";
export const REMOVE_FILLING: "REMOVE_FILLING" = "REMOVE_FILLING";
export const UPDATE_FILLING: "UPDATE_FILLING" = "UPDATE_FILLING";

export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";

export const ACTIVE_TAB_BAR: "ACTIVE_TAB_BAR" = "ACTIVE_TAB_BAR";

export const LOGOUT: "LOGOUT" = "LOGOUT";

export const MAKE_ORDER: "MAKE_ORDER" = "MAKE_ORDER";
export const MAKE_ORDER_SUCCESS: "MAKE_ORDER_SUCCESS" = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAILED: "MAKE_ORDER_FAILED" = "MAKE_ORDER_FAILED";
export const CLOSE_ORDER: "CLOSE_ORDER" = "CLOSE_ORDER";
export const SUM_ORDER: "SUM_ORDER" = "SUM_ORDER";

export const TOKEN: "TOKEN" = "TOKEN";
export const TOKEN_SUCCESS: "TOKEN_SUCCESS" = "TOKEN_SUCCESS";
export const TOKEN_FAILED: "TOKEN_FAILED" = "TOKEN_FAILED";

export const REGISTER: "REGISTER" = "REGISTER";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";

export const LOGIN: "LOGIN" = "LOGIN";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILED: "LOGIN_FAILED" = "LOGIN_FAILED";

export const GET_USER: "GET_USER" = "GET_USER";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const EDIT: "EDIT" = "EDIT";
export const EDIT_SUCCESS: "EDIT_SUCCESS" = "EDIT_SUCCESS";
export const EDIT_FAILED: "EDIT_FAILED" = "EDIT_FAILED";

export const FORGOT: "FORGOT" = "FORGOT";
export const FORGOT_SUCCESS: "FORGOT_SUCCESS" = "FORGOT_SUCCESS";
export const FORGOT_FAILED: "FORGOT_FAILED" = "FORGOT_FAILED";

export const RESET: "RESET" = "RESET";
export const RESET_SUCCESS: "RESET_SUCCESS" = "RESET_SUCCESS";
export const RESET_FAILED: "RESET_FAILED" = "RESET_FAILED";
